  2024-03/feature/load-any-chartink-csv[m
  bugfix/j-01-horizontal-and-vertical-rows-records-not-same[m
  chartink-script-to-generate-watchlist[m
  chartink-scripts[m
  develop[m
* [32mext-01-able-to-change-page-bg[m
  feature/2024-02-load-file-onchange-without-submit-button[m
  feature/2024-03-nifty-banknifty-average-move-details[m
  j/daily-screener-generate-watchlist[m
  j/feature/chartink-watchlist-generator[m
  j/intraday-screener[m
  main[m
  modal-popup-testing[m
  pre-main-merge[m
  screener-test[m
  temp[m
  test[m
  test-cases[m
  testing[m
  v-01-stocks-filter-by-name[m
  v-01-watchlist-generator[m
